# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author:
  name: Toms Tērauds
  email: "tomsterauds@gmail.com"

title: Portfolio
email: tomsterauds@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my programming portfolio! Here, 
  I showcase my programming projects, demonstrating my skills, and problem-solving abilities. 
  Gain insights into my approach, methodologies, and the technologies I use. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: TomTeraud

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Social networks
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/TomTeraud" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/toms-terauds" }


# # Custom translations
# i18n:
#   posts: "Projects"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # author: "Toms"

  - scope:
      path: "assets/img"
    values:
      image: true



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - quiz-results/
